const SNACK = {
  APP_NAME: 'SNACK CRM',
  TIMEZONE: 'America/Los_Angeles',
  SHEETS: {
    CONTACTS: 'Contacts',
    APPOINTMENTS: 'Appointments',
    TASKS: 'Tasks',
    PROGRAMS: 'Programs',
    KPI_DATA: 'KPI Data',
    OUTREACH: 'Outreach',
    STAFF: 'Staff',
    SETTINGS: 'Settings'
  },
  TASK_STATUS: {
    NOT_STARTED: 'Not Started',
    IN_PROGRESS: 'In Progress',
    COMPLETED: 'Completed',
    DEFERRED: 'Deferred'
  },
  APPOINTMENT_STATUS: {
    SCHEDULED: 'Scheduled',
    COMPLETED: 'Completed',
    NO_SHOW: 'No Show',
    CANCELLED: 'Cancelled',
    RESCHEDULED: 'Rescheduled'
  },
  CONTACT_STATUS: {
    SCHEDULED: 'Scheduled',
    ACTIVE: 'Active',
    NEEDS_RESCHEDULE: 'Needs Reschedule',
    WAITING_ON_FAMILY: 'Waiting on Family',
    NEEDS_LANGUAGE_SUPPORT: 'Needs Language Support',
    GRADUATED: 'Graduated',
    INACTIVE: 'Inactive',
    CLOSED: 'Closed / No Further Outreach'
  },
  DEFAULT_STAFF: 'Unassigned'
};

const HEADERS = {
  Contacts: [
    'ContactID',
    'First Name',
    'Last Name',
    'DOB',
    'Phone',
    'Email',
    'Address',
    'Language',
    'Parent/Guardian Name',
    'Preferred Contact Method',
    'SMS Consent',
    'Email Consent',
    'YCCO Status',
    'Category',
    'Status',
    'Referral Source',
    'Referral Type',
    'Referral Detail',
    'Reschedule Reason',
    'First Appointment Date',
    'Most Recent Contact Date',
    'Current Lesson Number',
    'Current Lesson Topic',
    'Last Goal',
    'Next Appointment Date',
    'Last Appointment Date',
    'No Show Count',
    'Completed Appointment Count',
    'Completion Date',
    'Inactive Reason',
    'Outcome Data Complete',
    'Notes',
    'Tags',
    'Created At',
    'Updated At'
  ],
  Appointments: [
    'AppointmentID',
    'ContactID',
    'Appointment Type',
    'Date',
    'Time',
    'Staff',
    'Status',
    'Lesson Number',
    'Lesson Topic',
    'Previous Goal',
    'Goal',
    'New Goal',
    'Next Appointment Scheduled',
    'Chart Note Complete',
    'Forms Due',
    'Arrived At',
    'Notes',
    'Calendar Event ID',
    'Created At',
    'Updated At'
  ],
  Tasks: [
    'TaskID',
    'Task Type',
    'Description',
    'ContactID',
    'AppointmentID',
    'Assigned Staff',
    'Priority',
    'Due Date',
    'Status',
    'Created By Automation',
    'Notes',
    'Created At',
    'Updated At',
    'Completed At'
  ],
  Programs: [
    'ProgramID',
    'Program Name',
    'Active Status',
    'Start Date',
    'End Date',
    'KPI Definitions',
    'Created At',
    'Updated At'
  ],
  'KPI Data': [
    'EntryID',
    'ProgramID',
    'KPI Name',
    'KPI Value',
    'Date',
    'Staff',
    'Notes',
    'Created At',
    'Updated At'
  ],
  Outreach: [
    'OutreachID',
    'Event Name',
    'Outreach Type',
    'Date',
    'Leads Generated',
    'Conversions',
    'Partner Organization',
    'Notes',
    'Created At',
    'Updated At'
  ],
  Staff: [
    'StaffID',
    'Name',
    'Role',
    'Email',
    'Availability',
    'Assigned Programs',
    'Active',
    'Created At',
    'Updated At'
  ],
  Settings: [
    'SettingID',
    'Setting Type',
    'Name',
    'Value',
    'Active',
    'Notes',
    'Updated At'
  ]
};

const DEFAULT_SETTINGS = [
  ['appointment_type', 'Enrollment', 'Enrollment', true, 'Creates intake/form prep workflow.'],
  ['appointment_type', 'Nutrition Lesson', 'Nutrition Lesson', true, 'Standard client lesson.'],
  ['appointment_type', 'Graduation', 'Graduation', true, 'Creates graduation/form workflow.'],
  ['appointment_type', 'Check-In', 'Check-In', true, 'Flexible support visit.'],
  ['task_type', 'Chart Note', 'Chart Note', true, 'Athena charting task.'],
  ['task_type', 'Form Entry', 'Form Entry', true, 'Google Form or paper form entry.'],
  ['task_type', 'Assessment Entry', 'Assessment Entry', true, 'Assessment entry workflow.'],
  ['task_type', 'Referral Follow-Up', 'Referral Follow-Up', true, 'Referral outreach follow-up.'],
  ['task_type', 'Client Follow-Up', 'Client Follow-Up', true, 'Client outreach follow-up.'],
  ['task_type', 'Outreach Follow-Up', 'Outreach Follow-Up', true, 'Public/professional outreach follow-up.'],
  ['task_type', 'Scheduling', 'Scheduling', true, 'Appointment scheduling task.'],
  ['task_type', 'Administrative', 'Administrative', true, 'Internal admin task.'],
  ['priority', 'High', 'High', true, 'Important or time-sensitive.'],
  ['priority', 'Normal', 'Normal', true, 'Default priority.'],
  ['priority', 'Low', 'Low', true, 'Lower urgency.'],
  ['contact_status', 'Scheduled', 'Scheduled', true, 'Appointment is scheduled.'],
  ['contact_status', 'Active', 'Active', true, 'Participating in the 8-appointment program.'],
  ['contact_status', 'Needs Reschedule', 'Needs Reschedule', true, 'Staff should help schedule the next appointment.'],
  ['contact_status', 'Waiting on Family', 'Waiting on Family', true, 'Family has the next step.'],
  ['contact_status', 'Needs Language Support', 'Needs Language Support', true, 'Needs interpreter or bilingual scheduling support.'],
  ['contact_status', 'Graduated', 'Graduated', true, 'Completed the program.'],
  ['contact_status', 'Inactive', 'Inactive', true, 'Paused or not currently participating, but may return.'],
  ['contact_status', 'Closed / No Further Outreach', 'Closed / No Further Outreach', true, 'Final outreach completed.'],
  ['referral_type', 'Internal provider referral', 'Internal provider referral', true, 'Referral from internal provider or SNACK bucket.'],
  ['referral_type', 'External clinic referral', 'External clinic referral', true, 'Referral from outside clinic.'],
  ['referral_type', 'Community organization referral', 'Community organization referral', true, 'Referral from partner organization.'],
  ['referral_type', 'Nutrition assessment', 'Nutrition assessment', true, 'Paper nutrition assessment entered by staff.'],
  ['referral_type', 'Self referral', 'Self referral', true, 'Family found SNACK and reached out directly.'],
  ['referral_type', 'Outreach event interest', 'Outreach event interest', true, 'Interested family from outreach event.'],
  ['referral_type', 'Hosted event/class interest', 'Hosted event/class interest', true, 'Interested family from SNACK-hosted event or class.'],
  ['referral_type', 'Other', 'Other', true, 'Referral source does not fit another option.'],
  ['contact_method', 'Text', 'Text', true, 'Prefers text messages.'],
  ['contact_method', 'Call', 'Call', true, 'Prefers phone calls.'],
  ['contact_method', 'Email', 'Email', true, 'Prefers email.'],
  ['workflow_rule', 'Referral follow-up days', '14', true, 'Create follow-up if not contacted in two weeks.']
];
